### PR TITLE
add a theme file

### PR DESCRIPTION
**Pull request by BrettBukowski**
abstracts away specific colors so we can make changes without having to touch each specific component

### CODE REVIEW

**Comment by BrettBukowski** [comment]
ready for review, @Ako0 @learningd3 :)

**Comment by mattam** [comment]
noice

**Comment by BrettBukowski** [comment]
not necessary for release - this is a cleanup after amanda's color changes land

**Comment by philipcdavis** [comment]
nice! Looks good

**Comment by Ako0** [comment]
sweet. just needs to be revisited after the new color changes go in. a bunch have been removed/changed.

**Pull request merged**
